Vision: 
  logcolor: "CYAN"
  tag_size: 65 #input in mm
  K: [1033.9140334285826, 0.0, 217.49962599879515, 0.0, 1027.3720125081963, 221.8851424617444, 0.0, 0.0, 1.0] #This needs to be in line 4, too lazy to dynamically check where attribute is stored.
  tag_to_search_for: 42 
  center: [0, 0]
  centerborders: [0.5, 0.8] # img percentages to consider 'centered'. if apriltag center is inside here, drop will commence. 
  target_threshold: 0.15 ##percentage of x resolution the camera considers "close enough" to drop. (0.1 = 10% of x image size. )
  
Camera:
  calibrated: False
  sensor_mode: 1 # set raw stream to 2304x1295px, 0x0 crop. (full FOV)
  resolution: [1280, 720]
  logcolor: "CYAN"
  imagepath: "./captures"
  libcameraloglevel: "3" #not working right now :( #"0" - DEBUG, "1" - INFO, "2" - WARN, "3" - ERROR, "4" - FATAL
  focal_length_pixels: 1000  # Example value, adjust based on your camera calibration
  frame_rate: 30.0  # Frame rate of the video in frames per second
  physical: [4.74, 6.45, 3.63] #Array to define the cameras physical attributes. Preset for the Raspberry Pi Camera Module v3. Order is: [Focal length in mm, sensorsizex, sensorsizey]
Helper: 
  logcolor: "CYAN"
  test: "Test"
Main:
  logcolor: "CYAN"
  fire_polling: 1
  afterrun_time: 5
  coolmode: True
  polling_timer: 0.2
Hardware:
  logcolor: "RED"
  camera_downtilt: 30.0
  camservo_angles: [10, 80]
  accellwaitpolling: 0.2 #time to poll for accell change during takeoff---
  zaccell: 0.2
  pumpinterval: 6.0 #time to take on water. shortened to stop lengthy runtimes...
  target_threshold: 0.1
  drop_servo: 1     #servo output which releases the payload. 
  cam_servo: 2      #servo output which controls the camera.
  drop_position: 12.5 #servo position which drops the payload. Range: dutycycle in %, for SG20 servos between 5.0 for minpos(0°) and 10.0 for maxpos(90°). 
  flying_position: 4.0
  mounting_position: 5.0
__main__: 
  logcolor: "BLUE"
User:
  debug: False
  log_level: 1