Vision: 
  logcolor: "CYAN"
  tag_size: 0.065
  K: [336.7755634193813, 0.0, 333.3575643300718, 0.0, 336.02729840829176, 212.77376312080065, 0.0, 0.0, 1.0]
  tag_to_search_for: 03 
Camera:
  logcolor: "CYAN"
  libcameraloglevel: "3" #not working right now :( #"0" - DEBUG, "1" - INFO, "2" - WARN, "3" - ERROR, "4" - FATAL
Helper: 
  logcolor: "CYAN"
Main:
  logcolor: "CYAN"
Hardware:
  camera_uptilt: 30.0

__main__: 
  logcolor: "CYAN"