Vision: 
  logcolor: "CYAN"
  tag_size: 0.065
  K: [1033.9140334285826, 0.0, 217.49962599879515, 0.0, 1027.3720125081963, 221.8851424617444, 0.0, 0.0, 1.0] #This needs to be in line 4, too lazy to dynamically check where attribute is stored.
  tag_to_search_for: 03 
  center: [0, 0]
  centerborders: [0.8, 0.8] # img percentages to consider 'centered'. if apriltag center is inside here, drop will commence. 
  target_threshold: 0.1
  
Camera:
  calibrated: False
  logcolor: "CYAN"
  imagepath: "./captures"
  libcameraloglevel: "3" #not working right now :( #"0" - DEBUG, "1" - INFO, "2" - WARN, "3" - ERROR, "4" - FATAL
  focal_length_pixels: 1000  # Example value, adjust based on your camera calibration
  frame_rate: 30.0  # Frame rate of the video in frames per second
  physical: [4.74, 714.2341, 1920, 1080] #Array to define the cameras physical attributes. Preset for the Raspberry Pi Camera Module v3. Order is: [Focal length in mm, pixels/mm for imgsize, image size x, image size y]
Helper: 
  logcolor: "CYAN"
  test: "Test"
Main:
  logcolor: "CYAN"
  fire_polling: 1
  afterrun_time: 10
  coolmode: True
  polling_timer: 5
Hardware:
  logcolor: "CYAN"
  camera_uptilt: 30.0
  accellwaitpolling: 0.2 #time to poll for accell change during takeoff---
  zaccell: 0.2
  pumpinterval: 0   #time to take on water. shortened to stop lengthy runtimes...
  target_threshold: 0.1
  drop_servo: 1     #servo output which releases the payload. 
  drop_position: 10 #servo position which drops the payload. Range: dutycycle in %, for SG20 servos between 5.0 for minpos(0°) and 10.0 for maxpos(90°). 
__main__: 
  logcolor: "BLUE"
User:
  debug: True
  log_level: 1